spring:
  application:
    name: hyundai
    # jdbc:mysql://database1.cypyubct4thy.ap-northeast-2.rds.amazonaws.com:3306
  datasource:
    url: jdbc:mysql://database1.cypyubct4thy.ap-northeast-2.rds.amazonaws.com:3306/database1
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: msung99 # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: msung6924 # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver

  file:
    /json

  jpa:
    hibernate:
      ddl-auto=update:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # API Key 유출 방지
  profiles:
    include: API-KEY


cloud:
  aws:
    credentials:
      access-key: AKIAZLIPYGMP3BDPYXYW
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: hyundai-bucket-test
    stack:
      auto: false


subKey: sk-1VjSlPA1LFqA3ddGyIZBT3BlbkFJRfkN
lastKey: Bn5G7hInruek3ZCi

# ${subKey}${lastKey}

openai:
  api-key: "${subKey}${lastKey}"

chatgpt:
  api-key: "${subKey}${lastKey}"


