spring:
  application:
    name: hyundai

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.cypyubct4thy.ap-northeast-2.rds.amazonaws.com:3306/database-1
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: admin # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: msung6924 # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


cloud:
  aws:
    credentials:
      access-key: AKIAZLIPYGMP3BDPYXYW
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: hyundai-bucket-test
    stack:
      auto: false

#  AKIAZLIPYGMP4NM5JAVL
#  z889D4xLWYrlPdbF4hu4emHioP7oVi5zBQ0Btd5J